bitsacco/os

apps/api/src/swap/swap.controller.spec.ts, apps/api/src/swap/swap.controller.ts, apps/api/src/swap/swap.service.spec.ts, apps/api/src/swap/swap.service.ts, apps/swap/src/fedimint/fedimint.service.ts, apps/swap/src/fx/fx.service.ts, apps/swap/src/swap.controller.ts, apps/swap/src/swap.service.ts, compose.yml, libs/common/src/dto/create-offramp-swap.dto.ts, libs/common/src/dto/create-onramp-swap.dto.ts, libs/common/src/dto/index.ts, libs/common/src/dto/quote.dto.ts, libs/common/src/types/proto/swap.ts, libs/common/src/utils/currency.ts, proto/swap.proto
this covers the rest api, with no implementations in the swap service
=> feat: declare offramp swap api

apps/api/src/admin/admin.controller.spec.ts, apps/api/src/admin/admin.controller.ts, apps/api/src/admin/admin.service.spec.ts, apps/api/src/admin/admin.service.ts, apps/api/src/api.module.ts, apps/api/src/main.ts, libs/common/src/types/api.ts
=> feat: mock app service

apps/shares/src/shares.service.ts, libs/common/src/types/proto/shares.ts, proto/shares.proto
=> refactor: return timestamp fields

apps/api/.dev.env, apps/api/src/api.module.ts, apps/api/src/auth/auth.controller.spec.ts, apps/api/src/auth/auth.controller.ts, apps/api/src/auth/auth.service.spec.ts, apps/api/src/auth/auth.service.ts, apps/auth/.dev.env, apps/auth/src/auth.controller.ts, apps/auth/src/auth.module.ts, apps/auth/src/auth.service.ts, apps/auth/src/users/users.service.ts, libs/common/src/auth/index.ts, libs/common/src/database/users.schema.ts, libs/common/src/dto/auth.dto.ts, libs/common/src/dto/swap.dto.ts, libs/common/src/index.ts, libs/common/src/types/auth.ts, libs/common/src/types/index.ts, libs/common/src/types/proto/auth.ts, libs/common/src/utils/index.ts, libs/common/src/utils/jwt-auth.guard.ts, proto/auth.proto
- proxy user `/register`, `/login`, `/verify` and `/authenticate` flows in rest api gateway
- set `Authentication` cookie on successful auth : `/login` or `/authenticate`
=> feat: progressive auth service

apps/solowallet/src/solowallet.service.ts
=> fix: solowallet withdraw to mpesa or lightning

apps/api/src/auth/auth.controller.ts, apps/auth/src/auth.module.ts, apps/auth/src/auth.service.ts, compose.yml, libs/common/src/users/users.service.ts
=> fix: integrate user registration/validation with sms otp

apps/shares/src/shares.service.ts
=> feat: filter out transactions with status UNRECOGNIZED

apps/auth/README.md, docs/contributing.md
- add `auth` service docs  for publishing
- add docs detailing how to interact with nest services from cli
=> docs: minor doc updates

apps/solowallet/src/solowallet.service.ts
=> feat: add param to list most recent activeTx first

libs/common/src/chamas/chamas.repository.ts, libs/common/src/chamas/chamas.service.spec.ts, libs/common/src/chamas/chamas.service.ts, libs/common/src/chamas/index.ts, libs/common/src/database/chamas.schema.ts, libs/common/src/database/index.ts, libs/common/src/database/users.schema.ts, libs/common/src/dto/chama.dto.ts, libs/common/src/dto/index.ts, libs/common/src/types/index.ts, libs/common/src/types/proto/chama.ts, proto/chama.proto
=> feat: define chama service api

apps/api/src/api.module.ts, apps/api/src/chamas/chamas.controller.spec.ts, apps/api/src/chamas/chamas.controller.ts, apps/api/src/swap/swap.controller.ts, apps/api/src/users/users.controller.spec.ts, apps/api/src/users/users.controller.ts, libs/common/src/chamas/chamas.service.ts, libs/common/src/dto/chama.dto.ts, libs/common/src/index.ts, libs/common/src/types/proto/chama.ts, libs/common/src/users/users.service.ts, proto/chama.proto
=> feat: define chama service endpoints in api gateway

apps/chama/src/chamas/db/chamas.schema.ts, compose.yml
- change allows a member to belong to multiple chamas
=> fix: non-unique chama memberships

apps/api/src/chamas/chamas.controller.spec.ts, apps/api/src/chamas/chamas.controller.ts, apps/api/src/main.ts, apps/api/src/nostr/nostr.controller.spec.ts, apps/api/src/nostr/nostr.controller.ts, apps/api/src/shares/shares.controller.spec.ts, apps/api/src/shares/shares.controller.ts, apps/api/src/sms/sms.controller.spec.ts, apps/api/src/sms/sms.controller.ts, apps/api/src/solowallet/solowallet.controller.spec.ts, apps/api/src/solowallet/solowallet.controller.ts, apps/api/src/swap/swap.controller.spec.ts, apps/api/src/swap/swap.controller.ts, apps/api/src/users/users.controller.spec.ts, apps/api/src/users/users.controller.ts, libs/common/src/auth/jwt.auth.ts, libs/testing/src/index.ts
=> feat: authenticate api endpoints

.github/workflows/publish-common.yml, .gitignore, CLAUDE.md, apps/api/src/auth/auth.controller.spec.ts, apps/auth/src/auth.service.spec.ts, apps/auth/src/tokens/token.service.spec.ts, libs/common/PUBLISH.md, libs/common/README.md, libs/common/package.json, libs/common/package.sh, libs/common/src/auth/jwt.auth.spec.ts, libs/common/src/database/token.repository.spec.ts, nest-cli.json
=> feat: publish @bitsacco/common npm package

package.json, seeders/README.md, seeders/chama-transactions.seeder.ts, seeders/chamas.seeder.ts, seeders/cli.ts, seeders/db.ts, seeders/index.ts, seeders/shares-offers.seeder.ts, seeders/solowallet-transactions.seeder.ts, seeders/types.ts, seeders/user-shares.seeder.ts, seeders/users.seeder.ts, seeders/utils.ts
=> feat: define seeders for local testing

apps/api/src/auth/auth.controller.spec.ts, apps/api/src/auth/auth.controller.ts
=> fix: bowser import

apps/api/src/auth/auth.controller.spec.ts, apps/api/src/auth/auth.controller.ts
=> chore: remove browser and agent detection

apps/swap/src/intasend/intasend.service.ts, apps/swap/src/swap.service.ts
1. In intasend.service.ts:
- Fixed the callback processing to properly set the transaction state
- Added default state initialization using the batch state
- Added extensive logging to track state transitions
- Handled edge cases better with more robust error checking
2. In swap.service.ts:
- Improved the M-Pesa payment update processing
- Added detailed logging to track the transaction flow
- Fixed state transition tracking and verification
- Ensured the update properly propagates to the database
These changes will ensure that when IntaSend completes an M-Pesa transaction, the corresponding solowallet transaction is properly updated to COMPLETED status.
=> chore: polish intasend and fedimint services

apps/api/src/chamas/chamas.controller.ts, apps/chama/src/chama.controller.ts, apps/chama/src/chamas/chamas.messaging.ts, apps/chama/src/wallet/db/wallet.schema.ts, apps/chama/src/wallet/wallet.service.ts, libs/common/src/dto/chamawallet.dto.ts, libs/common/src/types/proto/chamawallet.ts, proto/chamawallet.proto
=> feat: implement chama withdraw request

apps/shares/src/shares.service.spec.ts, apps/shares/src/shares.service.ts
- Implemented logic to increment share offer's subscribed quantity when a share purchase is successfully completed
- Updates occur when shares transactions transition to COMPLETE or APPROVED status
- Added logic in both handleWalletTxForShares and updateShares methods
- Added robust error handling and logging
- Updated tests to verify correct behavior for all scenarios
- Added tests to verify subscribed quantity incrementing for COMPLETE status
- Added tests to verify no updates for PROCESSING, FAILED, or not found scenarios
- Manually tested with sample data to ensure consistency
=> Feat: Increment share offer subscribed quantity with successful purchase

apps/shares/src/shares.service.spec.ts, apps/shares/src/shares.service.ts
- Added validation to prevent subscribing to shares if the offer is fully subscribed
- Implemented quantity check when creating share offers to ensure quantity > 0
- Added detailed error messages with available shares information
- Added comprehensive test coverage for all scenarios
- Added tests for subscription validation with various scenarios:
- Successful subscription when shares are available
- Error when requested quantity exceeds available shares
- Error when offer is fully subscribed
- Error when offer doesn't exist
- Added tests for offer creation validation:
- Success with valid quantity
- Error with zero quantity
- Error with negative quantity
- All tests are passing successfully
=> Feat: Prevent shares subscription if offer is fully subscribed

apps/shares/src/shares.service.spec.ts, apps/shares/src/shares.service.ts
- Implemented restriction preventing a single user from owning more than 20% of all available shares
- Added validation in both subscription and transfer workflows
- Calculated maximum allowed shares as 20% of total shares offered across all offers
- Added detailed error messages with current holdings, requested quantity, and maximum allowed
- Added comprehensive test coverage for share ownership limits:
- Tests for successful subscriptions and transfers within limits
- Tests for subscriptions exceeding the 20% limit
- Tests for transfers that would cause recipients to exceed limits
- Tests for subscription and transfer scenarios with various constraints
- Tested with different share quantities and user holdings
- All tests are passing successfully
- Added checks in both subscribeShares …
=> Feat: Prevent user from holding more than 20% of all available shares

apps/notification/src/notification.module.ts, apps/notification/src/notification.service.spec.ts, apps/notification/src/notification.service.ts, apps/notification/src/ratelimit/index.ts, apps/notification/src/ratelimit/ratelimit.service.spec.ts, apps/notification/src/ratelimit/ratelimit.service.ts, libs/common/src/utils/index.ts, libs/common/src/utils/notification.spec.ts, libs/common/src/utils/notification.ts
1. User ID Resolution:
- Created a robust utility function extractUserIdFromEvent that can handle different event types
- Implemented validation for user IDs to ensure they're valid
- Updated the notification service to use this utility for all event handlers
2. Rate Limiting:
- Implemented a comprehensive RateLimitService with configurable rate limits
- Added support for different limits based on channel (SMS, NOSTR, IN_APP)
- Added support for different limits based on notification importance
- Implemented burst capacity to handle occasional spikes
- Added metrics and logging for rate-limited notifications
3. Notification Service Integration:
- Updated the notification service to apply rate limiting when sending notifications
- Improved error handling and logging for failed …
=> feat: notification service version 0.2

apps/api/src/api.module.ts, apps/api/src/notifications/notification.controller.spec.ts, apps/api/src/notifications/notification.controller.ts, apps/notification/src/dto/notification.dto.ts
- add notification controller and fix failing tests
=> feat: notification service v0.3

grafana/dashboards/business-metrics-dashboard.json, libs/common/src/monitoring/README.md, libs/common/src/monitoring/business.metrics.ts, libs/common/src/monitoring/index.ts, libs/common/src/monitoring/transaction.metrics.ts
1. Created a comprehensive TransactionMetricsService for cross-service transaction tracking
2. Implemented BusinessMetricsService for user engagement and feature usage tracking
3. Designed Grafana dashboard for business metrics visualization
4. Added documentation with usage examples
=> feat: improve business and transaction metrics

apps/swap/src/swap.service.ts
Refactor onramp swap processing to properly handle state transitions when `MpesaTransactionState.Complete` is received. The swap now transitions to `PROCESSING` state before triggering actual `swapToBtc`, providing better visibility into the swap progression and improved error handling.
=> feat: improve swap state transitions and error handling

README.md
- https://github.com/minmoto/os has been archived in favor of a new workspace at https://github.com/minmoto/bitsaccoserver
=> chore: create a checkpoint referencing new repository

src/swap/swap.service.spec.ts, src/swap/swap.service.ts
The `FedimintService.receive()` method emits the `fedimint_receive_success` event multiple times as a lightning payment transitions through different states ('funded', 'awaiting-funds', 'claimed').
**The fix involves:**
1. Atomic state transition: Using `findOneAndUpdate` with a condition to atomically change the swap state from `PENDING` to `PROCESSING`, preventing race conditions.
2. Duplicate event protection: If the swap is not in `PENDING` state (meaning it's already been processed), the handler returns early and logs a warning.
This ensures that even if the `fedimint_receive_success` event is emitted multiple times, only the first one will trigger an Intasend payment, preventing duplicate withdrawals.
=> fix: atomic state updates and payouts for on and offramps

src/swap/swap.service.ts
Summary of Fix
I've successfully fixed the race condition issue in the swap webhook handler. The problem was that when Intasend sent a COMPLETE webhook for a payment, the system would reject it if
the swap was already in PROCESSING state (from a previous webhook).
`Changes made:
1. Modified processMpesaCollectionUpdate method in /src/swap/swap.service.ts:
- Added explicit handling for swaps already in PROCESSING state when receiving a COMPLETE webhook
- The system now properly completes the lightning payment even if the swap is already in PROCESSING state
- Added better state checks to prevent processing already completed or failed swaps
Key improvements:
- When a COMPLETE webhook arrives and the swap is in PROCESSING state, it now:
- Logs that it's completing the lightning payment
- …
=> fix: process mpesa collection update pays for invoices

src/lnurl/controllers/lnurlp.controller.spec.ts, src/lnurl/controllers/lnurlp.controller.ts, src/lnurl/lnurl.module.ts, src/personal/db/index.ts, src/personal/db/withdrawal-rate-limit.repository.ts, src/personal/db/withdrawal-rate-limit.schema.ts, src/personal/personal.module.ts, src/personal/services/atomic-withdrawal.service.simple.spec.ts, src/personal/services/atomic-withdrawal.service.spec.ts, src/personal/services/atomic-withdrawal.service.ts, src/personal/services/distributed-lock.service.spec.ts, src/personal/services/distributed-lock.service.ts, src/personal/services/index.ts, src/personal/services/wallet.service.ts, src/personal/services/withdrawal-monitor.service.ts, src/personal/services/withdrawal-rate-limit.service copy.ts, src/personal/services/withdrawal-rate-limit.service.ts, tsconfig.json
- Implement atomic withdrawal service with MongoDB-based distributed locking
- Add withdrawal monitor service for suspicious pattern detection
- Fix TOCTOU vulnerability allowing users to exceed wallet balance via concurrent requests
- Replace non-atomic balance checking with version-based optimistic locking
- Add multi-layer rate limiting for withdrawal endpoints
- Start withdrawals in PROCESSING status instead of immediate COMPLETE
BREAKING: Withdrawals now require atomic balance validation
Security: Prevents financial theft through rapid concurrent withdrawal requests
=> fix: critical race condition in lightning withdrawal balance checks
